import Control.Exception

def main():
    a = "someValue"
    assert a == 42, "AssertionFailed"
    somethingElse()